name: Generate TSC Meeting Transcript

on:
  issues:
    types: [closed]

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-trancript:
    runs-on: ubuntu-latest

    if: contains(github.event.issue.labels.*.name, 'meeting')

    env:
      TRANSCRIPT_GENERATED: false

    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Generate transcript
        run: npm run generate:transcript
        env:
          TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          ID: ${{ secrets.DISCORD_CHANNEL_ID }}
          ISSUE_TITLE: ${{ github.event.issue.title }}

      - name: Configure Git identity
        run: |
          git config user.email "webpack[bot]@users.noreply.github.com"
          git config user.name "Webpack Bot"

      - name: Commit generated transcript (if changed)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Files changed."
            git add --all
            git commit -m 'Add ${{ github.event.issue.title }} transcript'
            echo "TRANSCRIPT_GENERATED=true" >> $GITHUB_ENV
          fi

      - name: Create Pull Request
        if: env.TRANSCRIPT_GENERATED == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          base: 'main'
          commit-message: Add ${{ github.event.issue.title }} transcript
          title: Add ${{ github.event.issue.title }} transcript
          branch: generate-meeting-transcript
          branch-suffix: timestamp
          author: Webpack Bot <webpack[bot]@users.noreply.github.com>
          committer: Webpack Bot <webpack[bot]@users.noreply.github.com>
          body: |
            Add ${{ github.event.issue.title }} transcript.

            This PR is autogenerated by the "Generate Transcript" GitHub Action.
        env:
          GH_TOKEN: ${{ secrets.WEBPACK_GITHUB_BOT_TOKEN }}
