name: Generate TSC Meeting Agenda

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  meeting:
    runs-on: ubuntu-latest

    steps:
      - name: Webpack TSC Meeting Agenda
        uses: 'pkgjs/meet@v0'
        with:
          issueTitle: 'TSC Meeting <%= date.toFormat("dd-MMMM-yyyy") %>'
          token: ${{ secrets.WEBPACK_GITHUB_BOT_TOKEN }}
          orgs: webpack,webpack-contrib
          agendaLabel: 'tsc-agenda'
          meetingLabels: 'meeting'
          schedules: '2025-05-05T17:00:00.0Z/P2W'
          createWithin: 'P7D'
          issueTemplate: 'meeting-agenda.md'
